### ISSUE TITLE
🐞 BUG: Deploy Credentials 오류

### ISSUE THREAD

**Issue by JeekLee** [ProjectBlueHair/FinalProject_BE#8]
## Description
Deploy Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers

## 재현 과정
어떤 상황에 버그가 발생하는지 작성하세요.
1. 'Pull Request' 사용 시
2.  Deploy가 작동하지 않음

## 예상하는 정상 작동
Deploy 동작

## 스크린샷
![image](https://user-images.githubusercontent.com/72681875/209779948-85c661a8-9fa6-430a-9628-a99b9817a693.png)

## 버그 환경
- deploy.yml
```
    # (4) AWS 인증 (IAM 사용자 Access Key, Secret Key 활용)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
```
